// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `calculatorICE.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public interface CalculatorPrx extends Ice.ObjectPrx
{
    public int gcd(int num1, int num2);

    public int gcd(int num1, int num2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_gcd(int num1, int num2);

    public Ice.AsyncResult begin_gcd(int num1, int num2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_gcd(int num1, int num2, Ice.Callback __cb);

    public Ice.AsyncResult begin_gcd(int num1, int num2, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_gcd(int num1, int num2, Callback_Calculator_gcd __cb);

    public Ice.AsyncResult begin_gcd(int num1, int num2, java.util.Map<String, String> __ctx, Callback_Calculator_gcd __cb);

    public Ice.AsyncResult begin_gcd(int num1, 
                                     int num2, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_gcd(int num1, 
                                     int num2, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_gcd(int num1, 
                                     int num2, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_gcd(int num1, 
                                     int num2, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public int end_gcd(Ice.AsyncResult __result);

    public int lcd(int num1, int num2);

    public int lcd(int num1, int num2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_lcd(int num1, int num2);

    public Ice.AsyncResult begin_lcd(int num1, int num2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_lcd(int num1, int num2, Ice.Callback __cb);

    public Ice.AsyncResult begin_lcd(int num1, int num2, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_lcd(int num1, int num2, Callback_Calculator_lcd __cb);

    public Ice.AsyncResult begin_lcd(int num1, int num2, java.util.Map<String, String> __ctx, Callback_Calculator_lcd __cb);

    public Ice.AsyncResult begin_lcd(int num1, 
                                     int num2, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_lcd(int num1, 
                                     int num2, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_lcd(int num1, 
                                     int num2, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_lcd(int num1, 
                                     int num2, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public int end_lcd(Ice.AsyncResult __result);
}
