// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `CalculatorManager.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public interface _CalculatorOperations
{
    int gcd(int num1, int num2, Ice.Current __current);

    int lcm(int num1, int num2, Ice.Current __current);

    int factorial(int num1, Ice.Current __current);
}
