// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `CalculatorManager.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public interface CalculatorPrx extends Ice.ObjectPrx
{
    public int gcd(int num1, int num2);

    public int gcd(int num1, int num2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_gcd(int num1, int num2);

    public Ice.AsyncResult begin_gcd(int num1, int num2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_gcd(int num1, int num2, Ice.Callback __cb);

    public Ice.AsyncResult begin_gcd(int num1, int num2, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_gcd(int num1, int num2, Callback_Calculator_gcd __cb);

    public Ice.AsyncResult begin_gcd(int num1, int num2, java.util.Map<String, String> __ctx, Callback_Calculator_gcd __cb);

    public Ice.AsyncResult begin_gcd(int num1, 
                                     int num2, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_gcd(int num1, 
                                     int num2, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_gcd(int num1, 
                                     int num2, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_gcd(int num1, 
                                     int num2, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public int end_gcd(Ice.AsyncResult __result);

    public int lcm(int num1, int num2);

    public int lcm(int num1, int num2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_lcm(int num1, int num2);

    public Ice.AsyncResult begin_lcm(int num1, int num2, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_lcm(int num1, int num2, Ice.Callback __cb);

    public Ice.AsyncResult begin_lcm(int num1, int num2, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_lcm(int num1, int num2, Callback_Calculator_lcm __cb);

    public Ice.AsyncResult begin_lcm(int num1, int num2, java.util.Map<String, String> __ctx, Callback_Calculator_lcm __cb);

    public Ice.AsyncResult begin_lcm(int num1, 
                                     int num2, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_lcm(int num1, 
                                     int num2, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_lcm(int num1, 
                                     int num2, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_lcm(int num1, 
                                     int num2, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_IntCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public int end_lcm(Ice.AsyncResult __result);

    public int factorial(int num1);

    public int factorial(int num1, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_factorial(int num1);

    public Ice.AsyncResult begin_factorial(int num1, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_factorial(int num1, Ice.Callback __cb);

    public Ice.AsyncResult begin_factorial(int num1, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_factorial(int num1, Callback_Calculator_factorial __cb);

    public Ice.AsyncResult begin_factorial(int num1, java.util.Map<String, String> __ctx, Callback_Calculator_factorial __cb);

    public Ice.AsyncResult begin_factorial(int num1, 
                                           IceInternal.Functional_IntCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_factorial(int num1, 
                                           IceInternal.Functional_IntCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_factorial(int num1, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_IntCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_factorial(int num1, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_IntCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public int end_factorial(Ice.AsyncResult __result);
}
