// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `walkietalkie.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package walkietalkie;

public interface Communicator extends Ice.Object,
                                      _CommunicatorOperations, _CommunicatorOperationsNC
{
    public static final String ice_staticId = "::walkietalkie::Communicator";

    public static final long serialVersionUID = -5218760353941399317L;
}
